name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          python -m pip install -U codecov black isort pyproject-flake8
          npm install -g codecov

      - name: Install the widget extension
        run: |
          python -m pip install --upgrade -v -e ".[test, examples, docs]"

      - name: eslint linter
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          yarn run lint:check

      - name: black formatter
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: black --diff --check .

      - name: isort linter
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: isort --diff --check .

      - name: flake8 linter
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pflake8 .

      - name: Test the extension
        run: |
          python -m pytest
          yarn run test

      - name: Check docs can be build + links
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: docs
        run: |
          sudo apt install -y pandoc
          make html
          python -m pytest --check-links
